name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Test
        run: make test

  test-containers:
    strategy:
      matrix:
        include:
          - name: CentOS Stream 9
            image: quay.io/centos/centos:stream9
            pkg: dnf install -y gcc make
          - name: CentOS Stream 10
            image: quay.io/centos/centos:stream10
            pkg: dnf install -y gcc make
          - name: Fedora 42
            image: registry.fedoraproject.org/fedora:42
            pkg: dnf install -y gcc make
          - name: Fedora 43
            image: registry.fedoraproject.org/fedora:43
            pkg: dnf install -y gcc make
          - name: Amazon Linux 2023
            image: amazonlinux:2023
            pkg: dnf install -y gcc make
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: ${{ matrix.pkg }}

      - name: Build
        run: make

      - name: Test
        run: make test
